# Generated by Django 4.1.3 on 2022-11-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_file_task_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
