# Generated by Django 4.1.3 on 2022-11-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_file_alter_task_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='enrichments/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='enrichments/'),
        ),
    ]
