# Generated by Django 4.0.4 on 2022-10-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
